monolog:

    channels: ['interoperability', "reprise"]

    handlers:

        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks

        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!reprise"]

        interoperability:
            type: rotating_file
            process_psr_3_messages: false
            path: "%kernel.logs_dir%/import_interoperability_%kernel.environment%.log"
            level: error
            channels: ["interoperability"]

        reprise:
            type: rotating_file
            process_psr_3_messages: false
            path: "%kernel.logs_dir%/import_reprise_%kernel.environment%.log"
            level: error
            channels: ["reprise"]

